import { useMemo, useState } from 'react';
import { Download, FileText, LayoutDashboard, RefreshCw, UsersRound } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetAdminSummaryQueryKey, getListApplicationsQueryKey, getListJobsQueryKey, useDeleteJob, useGetAdminSummary, useListApplications, useListJobs, useUpdateJob } from '@workspace/api-client-react';
import { PageFrame, SectionKicker } from '@/components/layout';
import { Button, EmptyState, ErrorState, LoadingRows, StatusBadge } from '@/components/primitives';
import { JobCard } from '@/components/job-card';

export default function Admin() {
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<'summary' | 'jobs' | 'applications'>('summary');
  const summary = useGetAdminSummary();
  const jobs = useListJobs();
  const applications = useListApplications();
  const updateJob = useUpdateJob();
  const deleteJob = useDeleteJob();
  const [notice, setNotice] = useState('');
  const pendingJobs = useMemo(() => (jobs.data ?? []).filter((job) => job.status === 'Pending'), [jobs.data]);
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: getGetAdminSummaryQueryKey() }); void queryClient.invalidateQueries({ queryKey: getListJobsQueryKey() }); void queryClient.invalidateQueries({ queryKey: getListApplicationsQueryKey() }); };
  const changeStatus = (id: number, status: 'Approved' | 'Rejected') => updateJob.mutate({ id, data: { status } }, { onSuccess: () => { setNotice(status === 'Approved' ? 'Pozice byla schválena.' : 'Pozice byla zamítnuta.'); refresh(); } });
  const remove = (id: number) => { if (window.confirm('Opravdu chcete tuto nabídku smazat?')) deleteJob.mutate({ id }, { onSuccess: () => { setNotice('Pozice byla smazána.'); refresh(); } }); };
  return <PageFrame wide><div className="admin-head"><div><SectionKicker>Interní přehled</SectionKicker><h1>Moderace<br /><em>SalesHire.</em></h1></div><Button variant="secondary" onClick={refresh} data-testid="button-refresh-admin"><RefreshCw size={16} /> Obnovit data</Button></div>{notice ? <div className="admin-notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Zavřít oznámení" data-testid="button-dismiss-notice">×</button></div> : null}<nav className="admin-tabs" aria-label="Sekce administrace"><button className={tab === 'summary' ? 'active' : ''} onClick={() => setTab('summary')} data-testid="tab-admin-summary"><LayoutDashboard size={16} /> Přehled</button><button className={tab === 'jobs' ? 'active' : ''} onClick={() => setTab('jobs')} data-testid="tab-admin-jobs"><FileText size={16} /> Pozice <b>{pendingJobs.length}</b></button><button className={tab === 'applications' ? 'active' : ''} onClick={() => setTab('applications')} data-testid="tab-admin-applications"><UsersRound size={16} /> Reakce <b>{applications.data?.length ?? 0}</b></button></nav>
    {tab === 'summary' ? <section className="admin-content">{summary.isLoading ? <LoadingRows count={4} /> : summary.isError ? <ErrorState onRetry={() => summary.refetch()} /> : summary.data ? <><div className="summary-grid"><div className="summary-card summary-highlight"><span>Celkem pozic</span><strong>{summary.data.totalJobs}</strong><small>v databázi</small></div><div className="summary-card"><span>Čeká na kontrolu</span><strong>{summary.data.pendingJobs}</strong><small className="warning-text">vyžaduje pozornost</small></div><div className="summary-card"><span>Schváleno</span><strong>{summary.data.approvedJobs}</strong><small>zveřejněných</small></div><div className="summary-card"><span>Reakce kandidátů</span><strong>{summary.data.totalApplications}</strong><small>celkem</small></div></div><div className="admin-lower"><div><div className="section-heading compact"><div><SectionKicker>Fronta moderace</SectionKicker><h2>Co čeká na vás</h2></div><button className="inline-link-button" onClick={() => setTab('jobs')} data-testid="button-view-pending">Zobrazit vše →</button></div>{jobs.isLoading ? <LoadingRows /> : pendingJobs.length ? <div className="job-list compact-list">{pendingJobs.slice(0, 2).map((job) => <JobCard key={job.id} job={job} admin onApprove={() => changeStatus(job.id, 'Approved')} onReject={() => changeStatus(job.id, 'Rejected')} onDelete={() => remove(job.id)} />)}</div> : <EmptyState title="Fronta je prázdná" body="Všechny nabídky jsou zpracované." />}</div></div></> : null}</section> : null}
    {tab === 'jobs' ? <section className="admin-content"><div className="section-heading compact"><div><SectionKicker>Všechny nabídky</SectionKicker><h2>Moderace pozic</h2></div><span className="muted-copy">{jobs.data?.length ?? 0} záznamů</span></div>{jobs.isLoading ? <LoadingRows count={4} /> : jobs.isError ? <ErrorState onRetry={() => jobs.refetch()} /> : jobs.data?.length ? <div className="job-list">{jobs.data.map((job) => <JobCard key={job.id} job={job} admin onApprove={() => changeStatus(job.id, 'Approved')} onReject={() => changeStatus(job.id, 'Rejected')} onDelete={() => remove(job.id)} />)}</div> : <EmptyState title="Zatím žádné nabídky" body="Jakmile zaměstnavatelé odešlou první pozici, objeví se zde." />}</section> : null}
    {tab === 'applications' ? <section className="admin-content"><div className="section-heading compact"><div><SectionKicker>Přijaté reakce</SectionKicker><h2>Kandidáti</h2></div></div>{applications.isLoading ? <LoadingRows count={4} /> : applications.isError ? <ErrorState onRetry={() => applications.refetch()} /> : applications.data?.length ? <div className="applications-table">{applications.data.map((application) => <article className="application-row" key={application.id} data-testid={`row-application-${application.id}`}><div className="candidate-avatar">{application.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div><div className="application-main"><strong>{application.name}</strong><span>{application.jobTitle} · {application.companyName}</span></div><div className="application-contact"><a href={`mailto:${application.email}`} data-testid={`link-application-email-${application.id}`}>{application.email}</a>{application.phone ? <span>{application.phone}</span> : null}{application.cvFileName ? <span className="cv-file"><Download size={12} />{application.cvFileName}</span> : <span className="cv-missing">CV nepřiloženo</span>}</div><div className="application-date">{new Date(application.dateApplied).toLocaleDateString('cs-CZ')}</div></article>)}</div> : <EmptyState title="Zatím žádné reakce" body="Reakce kandidátů se po odeslání objeví zde." />}</section> : null}</PageFrame>;
}